# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftyCompanion' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

  # Pods for SwiftyCompanion
  pod 'Alamofire'
  pod 'AlamofireSwiftyJSON'
  pod 'AlamofireImage'
  pod 'DropDown'

end
